version: 0.2

env:
  variables:
    NODE_OPTIONS: '--openssl-legacy-provider'

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # install npm
      - npm install
      - npm install react-scripts --save

  build:
    commands:
      # run build script
      - npm run build

artifacts:
  files:
    - build/**/*
  base-directory: build
  discard-paths: yes
